version: "3"

services:
  nginx-proxy:
    build: proxy
    container_name: docker-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  portainer:
    image: portainer/portainer
    container_name: portainer-app
    restart: always
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    environment:
      - VIRTUAL_HOST=dock.localserver.net

  dnsmasq:
    build:
      context: .
      dockerfile: dns/Dockerfile
    container_name: dnsmasq-app
    cap_drop:
      - NET_ADMIN
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 5380:8080
    environment:
      - VIRTUAL_HOST=dns.localserver.net
      - "HTTP_USER=admin"
      - "HTTP_PASS=admin"

volumes:
  portainer_data:
  
networks:
  default:
    external:
      name: nginx-proxy